name: woo_api
description: >-
  Woocommerce rest api package.
version: 0.0.3
homepage: https://github.com/alfatihtalab/woo_api

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  http: ^1.1.0
  dio: ^5.1.1
  flutter:
    sdk: flutter
  retrofit: ^4.0.1
  meta: ^1.9.1
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
  retrofit_generator: ^7.0.8

